### ISSUE TITLE
搭建成功后feverapi设置相关的问题

### ISSUE THREAD

**Issue by zbuhui** [xizeyoupan/kinss#20]
你好，我在centos7上按照教程顺利安装，但是登陆x.x.x.x:5000点login后是这个页面。
https://img1.imgtp.com/2023/06/03/796P87bX.jpg
尝试设置后提交报错{"error":"status_code:404"}
没搞懂怎么设置了，能否出个详细的说明呢？谢谢

**Comment by xizeyoupan** [comment]
上面的图片是对的，报错可能是feverapi没写对，可以在[kinss.2333332.xyz](http://kinss.2333332.xyz)用readme中的例子试一下
