### ISSUE TITLE
Centos7系统部署失败

### ISSUE THREAD

**Issue by lockcp** [xizeyoupan/kinss#6]
1. 用docker部署之后无法访问，容器会停止运行
2. 用传统方式git了代码之后会提示缺少Pillow==7.2.0，安装pillow之后，能成功安装，但是用python ./app.py命令运行app.py会报错，还是运行不了，打开5000也无法访问，会提示No module named parse，把app.py中的urllib.parse更改为urlparse之后会提示SyntaxError: Non-ASCII character '\xe5' in file /utils.py on line 31, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details，在utils.py第一行加上-*- coding: utf-8 -*之后提示SyntaxError: invalid syntax。
不知道怎么才能搭建好kinss，希望作者看到能帮帮忙，谢谢♥

**Comment by xizeyoupan** [comment]
1.docker 有具体的报错吗
2.这是用python3写的，估计自带的是python2，不兼容，需要用python3运行。

**Comment by xizeyoupan** [comment]
docker 好像是有点问题，我晚点看看

**Comment by xizeyoupan** [comment]
现在docker应该可以了

**Comment by lockcp** [comment]
> 现在 docker 应该可以了

docker部署成功了，可以用了，谢谢大佬♥
